spring.application.name=taskmanagement

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA) configuration
spring.jpa.hibernate.ddl-auto=update

# Swagger
springdoc.api-docs.path=/v3/api-docs

# JWT
jwt.secret= ${JWT_SECRET}


