spring.application.name=taskmanagement

# PostgreSQL database connection
spring.datasource.url= jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username= postgres
spring.datasource.password= Str0ngP@ssw0rd!2025
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA) configuration
spring.jpa.hibernate.ddl-auto=validate

# Logging (optional for debugging)
# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate=INFO